### ISSUE TITLE
Database is undefined when using the postgresql driver

### ISSUE THREAD

**Issue by harianus** [postlight/lux#288] opened 2016-08-07 21:42 UTC
When using a postgresql database like this

``` js
// config/database.js
development: {
  driver: 'pg',
  username: 'postgres',
  host: '***',
  port: 5432,
  database: 'lux_database',
  password: '****'
},
```

But the database field is undefined here ([src/packages/database/utils/connect.js#L22](https://github.com/postlight/lux/blob/master/src/packages/database/utils/connect.js#L22)):

``` js
// node_modules/lux-framework/src/packages/database/utils/connect.js
const {
  host,
  socket,
  driver,
  database, // <--- undefined
  username,
  password
} = config;
```

Knex does then fallback to the current user of the OS which will likely be an incorrect database name.

**Comment by adampash** [comment] 2016-08-11 15:57
Hi @harianus! I've been looking into this and I can't seem to reproduce this bug using your config. Here's what I'm finding:

On `db:create` and `db:migrate`, the `database` field is undefined in [`connect.js`](https://github.com/postlight/lux/blob/master/src/packages/database/utils/connect.js#L22), but that's actually a necessity: On create, a database with that name doesn't yet exist (and so can't be connected to), and on drop, the database may exist but postgres can't drop a database it's connected to.

If you look at the connection made here https://github.com/postlight/lux/blob/master/src/packages/cli/commands/dbcreate.js#L24:

```javascript
    const { schema } = connect(CWD, { ...config, driver });
    const query = schema.raw(`CREATE DATABASE ${database}`);
```

While the database name isn't passed to connect (for the reason stated above), it is being used to create the database—and that's working fine for me. 

I realize I may be missing your issue, so if that's the case: Can you provide more details that help me reproduce?

**Comment by harianus** [comment] 2016-08-11 17:05
So the `db:migrate` command is working with the `database` field being `undefined`?

**Comment by harianus** [comment] 2016-08-11 17:16
The problem I'm having is just with the database connect function. But I will test my setup tomorrow again and will provide more details if the problem is still there. Maybe I did something wrong.

**Comment by adampash** [comment] 2016-08-11 18:49
@harianus The database field should not be undefined on db:migrate. In [`dbmigrate.js`](https://github.com/postlight/lux/blob/a8a5406995c3d1305057a3d0ebc965c103d8cdf8/src/packages/cli/commands/dbmigrate.js) the database field is passed in with the rest of the config object.

Let me know if that's not what you're seeing, though! We'll get to the bottom of this eventually!

**Comment by zacharygolba** [comment] 2016-08-12 14:12
Just a heads up @harianus. Since @adampash I were unable to reproduce this, I'm going to close this issue for now. We can help debug and work through this in the [Gitter](https://gitter.im/postlight/lux) room to find out the `database` is `undefined` for you. After debugging we can reopen this issue, or create a new one if necessary.

Thank you! 😃

**Comment by seawatts** [comment] 2016-12-14 20:11
Hmm, I'm having the same issue here as well.

**Comment by seawatts** [comment] 2016-12-16 21:18
I am still getting this same behavior it looks like it might have something to do with the NODE_ENV?

**Comment by seawatts** [comment] 2016-12-16 21:23
Here is the error I am getting on the elastic beanstalk cluster when I run `lux db:reset`

```
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: database "nodejs" does not exist
Error: Pool was destroyed
    at Pool._destroyPool (/var/app/current/node_modules/pool2/lib/pool.js:560:20)
    at Pool.<anonymous> (/var/app/current/node_modules/pool2/lib/pool.js:474:18)
    at Pool.<anonymous> (/var/app/current/node_modules/pool2/lib/pool.js:517:17)
    at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/var/app/current/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by seawatts** [comment] 2016-12-27 19:17
@zacharygolba any progress on this? Or ideas I could implement?

**Comment by zacharygolba** [comment] 2016-12-27 22:53
@seawatts I think this may be related to the prioritization of the config methods [in this file](https://github.com/postlight/lux/blob/master/src/packages/database/utils/connect.js#L44). I'm also skeptical that this ma be a rollup bug (the config could potentially get removed upon tree-shaking).

I do not have anything concrete started so if you want to give this a shot, be my guest. 😃

**Comment by seawatts** [comment] 2016-12-29 00:30
I think I found the culprit. 
When this line gets compiled: https://github.com/postlight/lux/blob/master/src/packages/cli/commands/dbdrop.js#L24

it turns into: 

```js
const a = createLoader(CWD)
              , {database:{[NODE_ENV]:{driver:b,database:c,url:d}}} = a('config');

const e = objectWithoutProperties(a('config').NODE_ENV.database, ['driver', 'database', 'url']);
```

And `a('config')` does not have `NODE_ENV` as a property on it so then it fails with 
`Cannot read property 'database' of undefined`

**Comment by zacharygolba** [comment] 2016-12-29 15:20
Excellent detective work @seawatts! This is starting to sound more familiar. There may be a fix in the `perf` branch.

Check out these files [`src/packages/cli/commands/dbcreate.js`](https://github.com/postlight/lux/blob/perf/src/packages/cli/commands/dbcreate.js) and [`src/packages/cli/commands/dbdrop.js`](https://github.com/postlight/lux/blob/perf/src/packages/cli/commands/dbdrop.js).

^ If that fixes the bug, feel free to PR those separately.

**Comment by nickschot** [comment] 2016-12-30 18:07
Seeing the same thing here with 1.1.1. Not happening with 1.1.0.

**Comment by seawatts** [comment] 2016-12-30 18:09
Verified that it is fixed in the `perf` branch

**Closed** 2017-01-04 00:43 UTC
Labels: bug
