### ISSUE TITLE
Partial updates with PATCH not working

### ISSUE THREAD

**Issue by carragom** [postlight/lux#719] opened 2017-08-13 18:49 UTC
*   **Platform**: Linux vm 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
*   **Database**: SQLite3
*   **Lux Version**: 1.2.1
*   **Node Version**: v6.11.0

Hey there,
How can I partially update a resource?. To see what I mean check [carragom/lux-patch](https://github.com/carragom/lux-patch) this is a simple Lux app with a `user` model and a `/users` endpoint. Once you have it running test the following:

### Create
Works as expected

    curl localhost:4000/users -X POST -H 'Content-Type: application/vnd.api+json' -d '{"data": {"type": "users", "attributes": {"login": "mylogin", "name": "My Name", "password": "secret"}}}'

### Full Update
Works as expected

    curl localhost:4000/users/1 -X PATCH -H 'Content-Type: application/vnd.api+json' -d '{"data": {"type": "users", "id": 1, "attributes": {"login": "newlogin", "name": "New Name", "password": "secret"}}}'

### Partial Update
**Does not work**. The partial update fails with the following error detail: "Missing required parameter 'data.attributes.login'.". From what I can read in the [JSONAPI spec](http://jsonapi.org/format/#crud-updating-resource-attributes), it should be possible to do partial resource updates. Am I missing something here?

    curl localhost:4000/users/1 -X PATCH -H 'Content-Type: application/vnd.api+json' -d '{"data": {"type": "users", "id": 1, "attributes": {"name": "Another Name"}}}'

### Delete
Works as expected

    curl localhost:4000/users/1 -X DELETE -H 'Accept: application/vnd.api+json'

**Comment by zacharygolba** [comment] 2017-08-28 21:15
@carragom I was able to reproduce this and it definitely is not the intended behavior. I just submitted a PR that fixes this issue (#721). Sorry it took so long!

**Comment by zacharygolba** [comment] 2017-08-28 22:23
This is fixed in [v1.2.2](https://github.com/postlight/lux/releases/tag/v1.2.2).

**Closed by zacharygolba** 2017-08-28 22:23 UTC
